#include <algorithm>
#include <array>
#include <bitset>
#include <chrono>
#include <cstdint>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <set>
#include <stdexcept>
#include <string>
#include <vector>
using namespace std;
using V3=array<int,3>;using M3=array<int,9>;using Hist=array<int,13>;
string W;array<V3,27>P;int ADD[27][27],THIRD[27][27];vector<M3>GL;vector<array<int,27>>GLMAP;vector<array<int,3>>T17;vector<array<int,4>>NORMALS;int DOT[40][81];
auto started=chrono::steady_clock::now();
double elapsed(){return chrono::duration<double>(chrono::steady_clock::now()-started).count();}
void guard(){if(elapsed()>570)throw runtime_error("REGISTERED_ENUMERATION_TIME_LIMIT");}
int mod(int x){x%=3;return x<0?x+3:x;}
int id(V3 a){return a[0]+3*a[1]+9*a[2];}
vector<int> pts(uint32_t mask){vector<int>p;for(int i=0;i<27;i++)if(mask>>i&1)p.push_back(i);return p;}
V3 act(const M3&M,V3 x){V3 y{};for(int i=0;i<3;i++)for(int j=0;j<3;j++)y[i]=mod(y[i]+M[3*i+j]*x[j]);return y;}
bool inverse(const M3&M,M3&L){int a[3][6]{};for(int i=0;i<3;i++){for(int j=0;j<3;j++)a[i][j]=M[3*i+j];a[i][i+3]=1;}for(int j=0;j<3;j++){int p=j;while(p<3&&a[p][j]==0)p++;if(p==3)return false;for(int k=0;k<6;k++)swap(a[p][k],a[j][k]);int v=a[j][j];for(int k=0;k<6;k++)a[j][k]=mod(a[j][k]*v);for(int i=0;i<3;i++)if(i!=j){v=a[i][j];for(int k=0;k<6;k++)a[i][k]=mod(a[i][k]-v*a[j][k]);}}for(int i=0;i<3;i++)for(int j=0;j<3;j++)L[3*i+j]=a[i][j+3];return true;}
template<class C>void arr(ostream&o,const C&v){o<<'[';bool first=true;for(auto x:v){if(!first)o<<',';first=false;o<<x;}o<<']';}
void pointarray(ostream&o,uint32_t m){o<<'[';bool first=true;for(int p:pts(m)){if(!first)o<<',';first=false;arr(o,P[p]);}o<<']';}
uint32_t extend_forbidden(uint32_t m,uint32_t forbid,int p){for(int q:pts(m))forbid|=1u<<THIRD[p][q];return forbid|m|(1u<<p);}
void subsets(uint32_t allowed,int target,const function<void(uint32_t)>&emit,uint32_t m=0,uint32_t forbid=0,int next=0,int n=0){if(n==target){emit(m);return;}uint32_t avail=allowed&~forbid&(~0u<<next);if(__builtin_popcount(avail)<target-n)return;while(avail){int p=__builtin_ctz(avail);avail&=avail-1;subsets(allowed,target,emit,m|(1u<<p),extend_forbidden(m,forbid,p),p+1,n+1);}}
struct Canon{uint32_t mask,representative;array<int,4>basis;M3 linear;V3 translation;};
Canon canonical(uint32_t m){Canon best{};best.mask=m;best.representative=~0u;auto p=pts(m);for(int o:p)for(int a:p)if(a!=o)for(int b:p)if(b!=o&&b!=a)for(int c:p)if(c!=o&&c!=a&&c!=b){M3 M{},L;for(int i=0;i<3;i++){M[3*i]=mod(P[a][i]-P[o][i]);M[3*i+1]=mod(P[b][i]-P[o][i]);M[3*i+2]=mod(P[c][i]-P[o][i]);}if(!inverse(M,L))continue;V3 v=act(L,P[o]);for(int&i:v)i=mod(-i);uint32_t out=0;for(int q:p){V3 x=act(L,P[q]);for(int i=0;i<3;i++)x[i]=mod(x[i]+v[i]);out|=1u<<id(x);}if(out<best.representative)best={m,out,{o,a,b,c},L,v};}if(best.representative==~0u)throw runtime_error("NONSPANNING_8_OR_9_CAP");return best;}
vector<uint32_t> classify(int n){vector<uint32_t>normalized;uint32_t basis=(1u<<0)|(1u<<1)|(1u<<3)|(1u<<9),forbid=basis;auto b=pts(basis);for(int x:b)for(int y:b)if(x!=y)forbid|=1u<<THIRD[x][y];uint32_t allowed=((1u<<27)-1)&~basis;subsets(allowed,n,[&](uint32_t m){normalized.push_back(m);},basis,forbid,0,4);sort(normalized.begin(),normalized.end());set<uint32_t>reps;ofstream f(W+"/normalized"+to_string(n)+".jsonl");size_t ct=0;for(auto m:normalized){if((ct++%20)==0)guard();Canon c=canonical(m);reps.insert(c.representative);f<<"{\"mask\":"<<m<<",\"canonical\":"<<c.representative<<",\"basis\":";arr(f,c.basis);f<<",\"linear\":";arr(f,c.linear);f<<",\"translation\":";arr(f,c.translation);f<<"}\n";}ofstream r(W+"/representatives"+to_string(n)+".json");r<<"{\"size\":"<<n<<",\"normalized_cap_count\":"<<normalized.size()<<",\"orbit_count\":"<<reps.size()<<",\"representatives\":[";bool first=true;for(auto m:reps){if(!first)r<<',';first=false;r<<"{\"mask\":"<<m<<",\"point_ids\":";arr(r,pts(m));r<<",\"points\":";pointarray(r,m);r<<'}';}r<<"]}\n";cerr<<"CLASSIFY "<<n<<" normalized "<<normalized.size()<<" orbits "<<reps.size()<<" seconds "<<elapsed()<<'\n';return vector<uint32_t>(reps.begin(),reps.end());}
struct Witness{uint32_t rep;int matrix,translation;};
vector<uint32_t> images(int n,const vector<uint32_t>&reps){map<uint32_t,Witness>all;for(auto rep:reps){auto pp=pts(rep);for(size_t g=0;g<GL.size();g++){if(g%1000==0)guard();for(int t=0;t<27;t++){uint32_t m=0;for(int p:pp)m|=1u<<ADD[GLMAP[g][p]][t];all.emplace(m,Witness{rep,(int)g,t});}}}ofstream f(W+"/actual"+to_string(n)+"_masks.txt"),q(W+"/actual"+to_string(n)+"_mappings.jsonl");vector<uint32_t>masks;for(auto[m,w]:all){masks.push_back(m);f<<m<<'\n';q<<"{\"mask\":"<<m<<",\"representative\":"<<w.rep<<",\"linear\":";arr(q,GL[w.matrix]);q<<",\"translation\":";arr(q,P[w.translation]);q<<"}\n";}cerr<<"IMAGES "<<n<<" actual "<<all.size()<<" seconds "<<elapsed()<<'\n';return masks;}
struct First{vector<int>pointids;string family;uint32_t A,B;};struct Generated{string family;uint32_t A,B;Hist h;};map<Hist,First>H;vector<Generated>GEN;map<string,size_t>FCOUNT;map<string,set<Hist>>FHIST;uint64_t PAIRCHECKS=0;
void capcheck4(const vector<int>&ps){bitset<81>m;for(int p:ps){if(m[p])throw runtime_error("DUPLICATE_POINT");m[p]=true;}for(size_t i=0;i<ps.size();i++)for(size_t j=0;j<i;j++){int a=ps[i],b=ps[j],third=0,pow=1;for(int k=0;k<4;k++){third+=mod(-(a%3)-(b%3))*pow;a/=3;b/=3;pow*=3;}if(m[third])throw runtime_error("NOT_A_17_CAP");PAIRCHECKS++;}}
void consume(const string&family,uint32_t A,uint32_t B,bool singleton){if(GEN.size()%1000==0)guard();vector<int>p;for(int x:pts(A))p.push_back(3*x);for(int x:pts(B))p.push_back(1+3*x);if(singleton)p.push_back(2);sort(p.begin(),p.end());if(p.size()!=17)throw runtime_error("WRONG_POINT_COUNT");capcheck4(p);Hist h{};for(int d=0;d<40;d++){array<int,3>ct{};for(int x:p)ct[DOT[d][x]]++;sort(ct.begin(),ct.end(),greater<int>());auto pos=find(T17.begin(),T17.end(),ct);if(pos==T17.end())throw runtime_error("BAD_HYPERPLANE_SIZE");h[pos-T17.begin()]++;}H.emplace(h,First{p,family,A,B});GEN.push_back({family,A,B,h});FCOUNT[family]++;FHIST[family].insert(h);}
void initialize(){for(int i=0;i<27;i++)P[i]={i%3,(i/3)%3,i/9};for(int a=0;a<27;a++)for(int b=0;b<27;b++){V3 c,d;for(int k=0;k<3;k++){c[k]=mod(P[a][k]+P[b][k]);d[k]=mod(-P[a][k]-P[b][k]);}ADD[a][b]=id(c);THIRD[a][b]=id(d);}for(int code=0;code<19683;code++){int q=code;M3 M,L;for(int&i:M){i=q%3;q/=3;}if(!inverse(M,L))continue;GL.push_back(M);array<int,27>perm;for(int p=0;p<27;p++)perm[p]=id(act(M,P[p]));GLMAP.push_back(perm);}if(GL.size()!=11232)throw runtime_error("GL_COUNT");for(int a=0;a<=9;a++)for(int b=0;b<=a;b++){int c=17-a-b;if(c>=0&&c<=b)T17.push_back({a,b,c});}if(T17.size()!=13)throw runtime_error("TYPE_COUNT");for(int code=1;code<81;code++){array<int,4>v;int q=code;for(int&i:v){i=q%3;q/=3;}int first=0;while(v[first]==0)first++;if(v[first]==1)NORMALS.push_back(v);}if(NORMALS.size()!=40)throw runtime_error("NORMAL_COUNT");for(int d=0;d<40;d++)for(int p=0;p<81;p++){int q=p,s=0;for(int k=0;k<4;k++){s+=NORMALS[d][k]*(q%3);q/=3;}DOT[d][p]=s%3;}}
int main(int argc,char**argv){if(argc!=2)return 2;W=argv[1];try{initialize();auto R8=classify(8),R9=classify(9);auto ALL8=images(8,R8),ALL9=images(9,R9);for(auto A:R9)for(auto B:ALL8)consume("980",A,B,false);cerr<<"FAMILY980 "<<FCOUNT["980"]<<" hist "<<FHIST["980"].size()<<" seconds "<<elapsed()<<'\n';for(auto A:R9){uint32_t neg=0;for(int a:pts(A)){V3 v=P[a];for(int&i:v)i=mod(-i);neg|=1u<<id(v);}subsets(((1u<<27)-1)&~neg,7,[&](uint32_t B){consume("971",A,B,true);});}cerr<<"FAMILY971 "<<FCOUNT["971"]<<" hist "<<FHIST["971"].size()<<" seconds "<<elapsed()<<'\n';for(auto A:R8){uint32_t neg=0;for(int a:pts(A)){V3 v=P[a];for(int&i:v)i=mod(-i);neg|=1u<<id(v);}subsets(((1u<<27)-1)&~neg,8,[&](uint32_t B){consume("881",A,B,true);});}cerr<<"FAMILY881 "<<FCOUNT["881"]<<" hist "<<FHIST["881"].size()<<" seconds "<<elapsed()<<'\n';map<Hist,int>ids;int i=0;for(auto&[h,f]:H)ids[h]=i++;ofstream out(W+"/histograms17.json");out<<"{\"status\":\"COMPLETE_AUTHOR_ENUMERATION_PENDING_INDEPENDENT_AUDIT\",\"coordinate_id_4d\":\"t+3*x+9*y+27*z\",\"types\":[";for(size_t j=0;j<T17.size();j++){if(j)out<<',';arr(out,T17[j]);}out<<"],\"histograms\":[";bool first=true;for(auto&[h,f]:H){if(!first)out<<',';first=false;out<<"{\"id\":"<<ids[h]<<",\"counts\":";arr(out,h);out<<",\"family\":\""<<f.family<<"\",\"A_mask\":"<<f.A<<",\"B_mask\":"<<f.B<<",\"point_ids\":";arr(out,f.pointids);out<<",\"points\":[";for(size_t j=0;j<f.pointids.size();j++){if(j)out<<',';int p=f.pointids[j];array<int,4>v;for(int&x:v){x=p%3;p/=3;}arr(out,v);}out<<"]}";}out<<"]}\n";ofstream ledger(W+"/generated17_ledger.tsv");ledger<<"family\tA_mask\tB_mask\thistogram_id\n";for(auto&g:GEN)ledger<<g.family<<'\t'<<g.A<<'\t'<<g.B<<'\t'<<ids[g.h]<<'\n';ofstream summary(W+"/enumeration_summary.json");summary<<"{\"status\":\"COMPLETE_AUTHOR_ENUMERATION_PENDING_INDEPENDENT_AUDIT\",\"orbit_count8\":"<<R8.size()<<",\"orbit_count9\":"<<R9.size()<<",\"actual8_count\":"<<ALL8.size()<<",\"actual9_count\":"<<ALL9.size()<<",\"GL3_count\":"<<GL.size()<<",\"AGL3_maps_per_representative\":"<<GL.size()*27<<",\"generated17_count\":"<<GEN.size()<<",\"distinct17_histograms\":"<<H.size()<<",\"point_pair_checks\":"<<PAIRCHECKS<<",\"elapsed_seconds\":"<<elapsed()<<",\"families\":{";first=true;for(auto&[s,n]:FCOUNT){if(!first)summary<<',';first=false;summary<<'"'<<s<<"\":{\"generated\":"<<n<<",\"histograms\":"<<FHIST[s].size()<<'}';}summary<<"}}\n";cerr<<"COMPLETE generated "<<GEN.size()<<" distinct_histograms "<<H.size()<<" seconds "<<elapsed()<<'\n';return 0;}catch(const exception&e){ofstream f(W+"/failure.json");f<<"{\"status\":\"INCOMPLETE\",\"reason\":\""<<e.what()<<"\",\"elapsed_seconds\":"<<elapsed()<<"}\n";cerr<<e.what()<<'\n';return 1;}}
